In [7]:
import polars as pl
from utils import target_encode_nominal_columns

df = pl.read_csv("../datasets/ca-dealers-used.csv")
df.head(2)

shape: (2, 21)
┌──────────────┬──────────────┬────────┬───────┬───┬──────────────┬──────────────┬───────┬─────────┐
│ id           ┆ vin          ┆ price  ┆ miles ┆ … ┆ street       ┆ city         ┆ state ┆ zip     │
│ ---          ┆ ---          ┆ ---    ┆ ---   ┆   ┆ ---          ┆ ---          ┆ ---   ┆ ---     │
│ str          ┆ str          ┆ i64    ┆ i64   ┆   ┆ str          ┆ str          ┆ str   ┆ str     │
╞══════════════╪══════════════╪════════╪═══════╪═══╪══════════════╪══════════════╪═══════╪═════════╡
│ b39ea795-eca ┆ 19UNC1B01HY8 ┆ 179999 ┆ 9966  ┆ … ┆ 475 Rue      ┆ Edmundston   ┆ NB    ┆ E3V 2K7 │
│ 9            ┆ 00062        ┆        ┆       ┆   ┆ Victoria     ┆              ┆       ┆         │
│ 026cb5b1-6e3 ┆ 19UNC1B02HY8 ┆ 179995 ┆ 5988  ┆ … ┆ 2795 Route-d ┆ Notre-dame-d ┆ QC    ┆ G0M 1K0 │
│ e            ┆ 00023        ┆        ┆       ┆   ┆ u-prsident-k ┆ es-pins      ┆       ┆         │
│              ┆              ┆        ┆       ┆   ┆ ennedy       ┆              ┆       ┆         │
└──────────────┴──────────────┴────────┴───────┴───┴──────────────┴──────────────┴───────┴─────────┘

In [8]:
# preprocessing
# drop unnecessary columns
df = df.drop(["id", "vin", "stock_no", "seller_name", "street", "zip"])
categorical_columns = ["make", "model", "trim", "body_type", "vehicle_type",
                     "drivetrain", "transmission", "fuel_type", "engine_block",
                     "city", "state"]
# drop nan categorical columns
df = df.drop_nulls(subset=categorical_columns + ["price"])
target = df["price"]
data = df.drop("price")
data.head(2)

shape: (2, 14)
┌───────┬──────┬───────┬───────┬───┬─────────────┬──────────────┬─────────────────────┬───────┐
│ miles ┆ year ┆ make  ┆ model ┆ … ┆ engine_size ┆ engine_block ┆ city                ┆ state │
│ ---   ┆ ---  ┆ ---   ┆ ---   ┆   ┆ ---         ┆ ---          ┆ ---                 ┆ ---   │
│ i64   ┆ i64  ┆ str   ┆ str   ┆   ┆ f64         ┆ str          ┆ str                 ┆ str   │
╞═══════╪══════╪═══════╪═══════╪═══╪═════════════╪══════════════╪═════════════════════╪═══════╡
│ 9966  ┆ 2017 ┆ Acura ┆ NSX   ┆ … ┆ 3.5         ┆ V            ┆ Edmundston          ┆ NB    │
│ 5988  ┆ 2017 ┆ Acura ┆ NSX   ┆ … ┆ 3.5         ┆ V            ┆ Notre-dame-des-pins ┆ QC    │
└───────┴──────┴───────┴───────┴───┴─────────────┴──────────────┴─────────────────────┴───────┘

In [9]:
# nominal_columns = ["make", "model", "body_type", "vehicle_type",
# save unique values to a dictionary
unique_values_dict = {}
for col in categorical_columns:
    unique_values = data[col].unique()
    unique_values_dict[col] = unique_values
# One-hot encode the nominal categorical columns

In [10]:
unique_values_dict["fuel_type"]

shape: (25,)
Series: 'fuel_type' [str]
[
	"Electric / Premium Unleaded"
	"Compressed Natural Gas / Unlea…
	"Premium Unleaded; Unleaded"
	"E85 / Unleaded; Unleaded"
	"E85 / Unleaded"
	…
	"Electric / Unleaded"
	"Diesel"
	"Electric / E85"
	"Compressed Natural Gas"
	"Compressed Natural Gas; Unlead…
]

In [ ]:
# convert nominal columns to target encoded columns
nominal_columns = ["make", "model", "trim", "body_type", "vehicle_type",
                   "fuel_type", "city", "state"]
target_encoded_data, target_encoders = target_encode_nominal_columns(data, target, nominal_columns)
# one-hot encode "transmission" and "drivetrain"
remaining_nominal_columns = ["transmission", "drivetrain", "engine_block"]
from utils import onehot_encode_nominal_columns
onehot_encoded_data, onehot_encoders = onehot_encode_nominal_columns(target_encoded_data, remaining_nominal_columns)
# convert ordindal columns to categorical codes

shape: (295_878, 22)
┌─────────┬────────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ miles   ┆ year   ┆ make       ┆ model      ┆ … ┆ engine_blo ┆ engine_blo ┆ engine_bl ┆ engine_bl │
│ ---     ┆ ---    ┆ ---        ┆ ---        ┆   ┆ ck_        ┆ ck_H       ┆ ock_I     ┆ ock_V     │
│ f64     ┆ f64    ┆ f64        ┆ f64        ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│         ┆        ┆            ┆            ┆   ┆ f64        ┆ f64        ┆ f64       ┆ f64       │
╞═════════╪════════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 9966.0  ┆ 2017.0 ┆ 26772.4681 ┆ 85126.3056 ┆ … ┆ 0.0        ┆ 0.0        ┆ 0.0       ┆ 1.0       │
│         ┆        ┆ 61         ┆ 79         ┆   ┆            ┆            ┆           ┆           │
│ 5988.0  ┆ 2017.0 ┆ 26772.4681 ┆ 85126.3056 ┆ … ┆ 0.0        ┆ 0.0        ┆ 0.0       ┆ 1.0       │
│         ┆        ┆ 61         ┆ 79         ┆   ┆            ┆            ┆           ┆           │
│ 24242.0 ┆ 2017.0 ┆ 26772.4681 ┆ 85126.3056 ┆ … ┆ 0.0        ┆ 0.0        ┆ 0.0       ┆ 1.0       │
│         ┆        ┆ 61         ┆ 79         ┆   ┆            ┆            ┆           ┆           │
│ 6637.0  ┆ 2020.0 ┆ 26772.4681 ┆ 85126.3056 ┆ … ┆ 0.0        ┆ 0.0        ┆ 0.0       ┆ 1.0       │
│         ┆        ┆ 61         ┆ 79         ┆   ┆            ┆            ┆           ┆           │
│ 6637.0  ┆ 2020.0 ┆ 26772.4681 ┆ 85126.3056 ┆ … ┆ 0.0        ┆ 0.0        ┆ 0.0       ┆ 1.0       │
│         ┆        ┆ 61         ┆ 79         ┆   ┆            ┆            ┆           ┆           │
│ …       ┆ …      ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ 22108.0 ┆ 2019.0 ┆ 43399.2542 ┆ 45725.1934 ┆ … ┆ 0.0        ┆ 0.0        ┆ 1.0       ┆ 0.0       │
│         ┆        ┆ 78         ┆ 96         ┆   ┆            ┆            ┆           ┆           │
│ 55316.0 ┆ 2018.0 ┆ 43399.2542 ┆ 45725.1934 ┆ … ┆ 0.0        ┆ 0.0        ┆ 1.0       ┆ 0.0       │
│         ┆        ┆ 78         ┆ 96         ┆   ┆            ┆            ┆           ┆           │
│ 55316.0 ┆ 2018.0 ┆ 43399.2542 ┆ 45725.1934 ┆ … ┆ 0.0        ┆ 0.0        ┆ 1.0       ┆ 0.0       │
│         ┆        ┆ 78         ┆ 96         ┆   ┆            ┆            ┆           ┆           │
│ null    ┆ 2020.0 ┆ 88174.2858 ┆ 88315.0466 ┆ … ┆ 0.0        ┆ 0.0        ┆ 0.0       ┆ 1.0       │
│         ┆        ┆ 44         ┆ 55         ┆   ┆            ┆            ┆           ┆           │
│ 7595.0  ┆ 2020.0 ┆ 88174.2858 ┆ 88315.0466 ┆ … ┆ 0.0        ┆ 0.0        ┆ 0.0       ┆ 1.0       │
│         ┆        ┆ 44         ┆ 55         ┆   ┆            ┆            ┆           ┆           │
└─────────┴────────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘